version: "3.9"

services:

  # -------------------------------------------------------
  # Rust API - Notification Service
  # -------------------------------------------------------
  rust-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paybridge-notification-service
    ports:
      - "8081:8081"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=no-reply@paybridge.local
    restart: unless-stopped
    networks:
      - paybridge_network

networks:
  paybridge_network:
    external: true