FROM rust:1.84-alpine AS builder

# Install MUSL tools
RUN apk add --no-cache musl-dev

WORKDIR /app

# Cache deps
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build

# Build actual project
COPY . .
RUN cargo build

# Final stage - fully static binary
FROM alpine:3.20
WORKDIR /app

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/insurance_claim_management_system app

EXPOSE 8081
CMD ["./app"]
